export const workers = [
  {
    name: "Blaise DEFLOO",
    role: "Manager",
    equipments: [
      { name: "Protective gloves", items: 0 },
      { name: "Safety glasses", items: 1, priority: "low" },
      { name: "Ear protection", items: 9, priority: "high" },
      { name: "Mask", items: 0 },
      { name: "Knee pads", items: 0 },
      { name: "Safety shoes", items: 10, priority: "high" },
      { name: "Coverall", items: 0 },
      { name: "Hi-Vis Jacket", items: 2, priority: "low" },
      { name: "Safety Harness", items: 0 },
      { name: "Face shield", items: 0 },
      { name: "Hard Hat", items: 0 },
      { name: "Welding helmet", items: 0 },
    ],
  },
  {
    name: "Blaise DEFLOO",
    role: "Manager",
    equipments: [
      { name: "Protective gloves", items: 3, priority: "high" },
      { name: "Safety glasses", items: 0 },
      { name: "Ear protection", items: 1, priority: "low" },
      { name: "Mask", items: 0 },
      { name: "Knee pads", items: 0 },
      { name: "Safety shoes", items: 0 },
      { name: "Coverall", items: 0 },
      { name: "Hi-Vis Jacket", items: 0 },
      { name: "Safety Harness", items: 2, priority: "high" },
      { name: "Face shield", items: 0 },
      { name: "Hard Hat", items: 0 },
      { name: "Welding helmet", items: 0 },
    ],
  },
  {
    name: "Ella SANDERS",
    role: "Worker",
    equipments: [
      { name: "Protective gloves", items: 0 },
      { name: "Safety glasses", items: 3, priority: "high" },
      { name: "Ear protection", items: 0 },
      { name: "Mask", items: 0 },
      { name: "Knee pads", items: 0 },
      { name: "Safety shoes", items: 0 },
      { name: "Coverall", items: 0 },
      { name: "Hi-Vis Jacket", items: 0 },
      { name: "Safety Harness", items: 0 },
      { name: "Face shield", items: 0 },
      { name: "Hard Hat", items: 2, priority: "high" },
      { name: "Welding helmet", items: 1, priority: "low" },
    ],
  },
  {
    name: "Logan MITCHELL",
    role: "Worker",
    equipments: [
      { name: "Protective gloves", items: 0 },
      { name: "Safety glasses", items: 0 },
      { name: "Ear protection", items: 3, priority: "high" },
      { name: "Mask", items: 0 },
      { name: "Knee pads", items: 0 },
      { name: "Safety shoes", items: 0 },
      { name: "Coverall", items: 0 },
      { name: "Hi-Vis Jacket", items: 2, priority: "low" },
      { name: "Safety Harness", items: 0 },
      { name: "Face shield", items: 0 },
      { name: "Hard Hat", items: 0 },
      { name: "Welding helmet", items: 0 },
    ],
  },
  {
    name: "Aria BAILEY",
    role: "Worker",
    equipments: [
      { name: "Protective gloves", items: 3, priority: "high" },
      { name: "Safety glasses", items: 0 },
      { name: "Ear protection", items: 0 },
      { name: "Mask", items: 0 },
      { name: "Knee pads", items: 0 },
      { name: "Safety shoes", items: 0 },
      { name: "Coverall", items: 0 },
      { name: "Hi-Vis Jacket", items: 0 },
      { name: "Safety Harness", items: 2, priority: "high" },
      { name: "Face shield", items: 0 },
      { name: "Hard Hat", items: 0 },
      { name: "Welding helmet", items: 0 },
    ],
  },
  {
    name: "Mason WALKER",
    role: "Worker",
    equipments: [
      { name: "Protective gloves", items: 1, priority: "low" },
      { name: "Safety glasses", items: 3, priority: "high" },
      { name: "Ear protection", items: 0 },
      { name: "Mask", items: 1, priority: "low" },
      { name: "Knee pads", items: 0 },
      { name: "Safety shoes", items: 0 },
      { name: "Coverall", items: 0 },
      { name: "Hi-Vis Jacket", items: 3, priority: "low" },
      { name: "Safety Harness", items: 0 },
      { name: "Face shield", items: 0 },
      { name: "Hard Hat", items: 0 },
      { name: "Welding helmet", items: 1, priority: "low" },
    ],
  },
  {
    name: "Lily KELLY",
    role: "Worker",
    equipments: [
      { name: "Protective gloves", items: 0 },
      { name: "Safety glasses", items: 1, priority: "low" },
      { name: "Ear protection", items: 0 },
      { name: "Mask", items: 0 },
      { name: "Knee pads", items: 1, priority: "low" },
      { name: "Safety shoes", items: 0 },
      { name: "Coverall", items: 0 },
      { name: "Hi-Vis Jacket", items: 0 },
      { name: "Safety Harness", items: 0 },
      { name: "Face shield", items: 0 },
      { name: "Hard Hat", items: 0 },
      { name: "Welding helmet", items: 10, priority: "high" },
    ],
  },
];

export const equipments = [
  { name: "Protective gloves", image: "/assets/equipment/1.png" },
  { name: "Safety glasses", image: "/assets/equipment/2.png" },
  { name: "Ear protection", image: "/assets/equipment/3.png" },
  { name: "Mask", image: "/assets/equipment/4.png" },
  { name: "Knee pads", image: "/assets/equipment/5.png" },
  { name: "Safety shoes", image: "/assets/equipment/6.png" },
  { name: "Coverall", image: "/assets/equipment/7.png" },
  { name: "Hi-Vis Jacket", image: "/assets/equipment/8.png" },
  { name: "Safety Harness", image: "/assets/equipment/9.png" },
  { name: "Face shield", image: "/assets/equipment/10.png" },
  { name: "Hard Hat", image: "/assets/equipment/11.png" },
  { name: "Welding helmet", image: "/assets/equipment/12.png" },
];
